modLoader="javafml"
loaderVersion="[4,)"
license="CC0-1.0"

[[mods]]
modId="kingdom_come_combat"
version="${version}"
displayName="Kingdom Come Combat"
authors="DUCK goose"
description='''Kingdom Come inspired directional combat for NeoForge.'''

[[dependencies.kingdom_come_combat]]
modId="neoforge"
type="required"
versionRange="[${neoforge_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.kingdom_come_combat]]
modId="minecraft"
type="required"
versionRange="[${minecraft_version}]"
ordering="NONE"
side="BOTH"

[[dependencies.kingdom_come_combat]]
modId="fabric_api"
type="required"
versionRange="[0.116.7,)"
ordering="NONE"
side="BOTH"

[[dependencies.kingdom_come_combat]]
modId="cloth_config"
type="required"
versionRange="[${cloth_config_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.kingdom_come_combat]]
modId="player_animation_library"
type="required"
versionRange="[1.1.4,)"
ordering="NONE"
side="BOTH"

[[dependencies.kingdom_come_combat]]
modId="firstaid"
type="optional"
versionRange="[1.2.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.kingdom_come_combat]]
modId="legendarysurvivaloverhaul"
type="optional"
versionRange="[2.4.0,)"
ordering="AFTER"
side="BOTH"

[[mixins]]
config="kingdom_come_combat.mixins.json"

[[mixins]]
config="kingdom_come_combat.client.mixins.json"
