org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
loom.platform=neoforge
org.gradle.java.installations.paths=/usr/local/opt/openjdk@21/libexec/openjdk.jdk/Contents/Home

minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
neoforge_version=21.1.235
forgified_fabric_api_version=0.116.7+2.2.4+1.21.1
forgified_fabric_loader_version=2.5.68+0.18.4+1.21.1
cloth_config_version=15.0.140
pal_version=1.1.4+mc.1.21.1
geckolib_version=4.8.2
mod_version=1.7.2
